CREATE DATABASE IF NOT EXISTS java CHARSET utf8mb4;

USE java;

CREATE TABLE IF NOT EXISTS `users`(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    `password` VARCHAR(100) NOT NULL
)Engine=InnoDB;